FROM ubuntu:20.04

LABEL maintainer="pgibbons312@gmail.com"
RUN yum update -y && \ yum install -y python3 python3-pip
COPY ./requirements.txt /app/requirements.txt
WORKDIR /app

RUN pip3 install -r requirements.txt
COPY . /app
ENTRYPOINT [ "python3" ]
CMD [ "app.py" ]
